/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_Main */

#ifndef _Included_main_Main
#define _Included_main_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main_Main
 * Method:    getTable
 * Signature: ()[[I
 */
JNIEXPORT jobjectArray JNICALL Java_main_Main_getTable
  (JNIEnv *, jclass);

/*
 * Class:     main_Main
 * Method:    makeMove
 * Signature: ([[I)Z
 */
JNIEXPORT jboolean JNICALL Java_main_Main_makeMove
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
